### ISSUE TITLE
Request for CUB Benchmark Source Code to Reproduce Results

### ISSUE THREAD

**Issue by gudhillon** [juliusikkala/fuchsia_radix_sort#2]
Hello,

I couldn’t find your CUB benchmark source files in the repository and wanted to ask if they’re publicly available. 

I’m interested in reproducing the graphs you’ve shared in the README for comparison on my end.

**Comment by juliusikkala** [comment]
I don't know, I did not run the benchmarks. Google developers did them. As you can see from the top of the README file, the original repository is on [googlesource.com](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/src/graphics/lib/compute/radix_sort). The part of the README file with the benchmarks was copied as-is from that upstream repository. This GitHub repository is a fork, where I've changed the build system from Gradle to CMake and made the shader loading part a little easier to integrate into other codebases.
